### ISSUE TITLE
self.root typing not recognized by IDE

### ISSUE THREAD

**Issue by lbelangers** [romis2012/pydantic-collections#5]
First of, great package, very useful.

When I'm iterating over a subclass of BaseModelCollection, I do not get recommandations based on the type hints of the assigned type. 

Example:
```
from pydantic_collections import BaseCollectionModel
from pydantic import BaseModel

class Car(BaseModel):
   speed: float

class CarCollection(BaseCollectionModel[Car]):
   pass

car_collection = CarCollection([Car(speed = 60.0)])

for car in car_collection:
   print(car)
```
I get no type hints from my IDE, so it is not able to give me recommandations about the attributes of the element in the collection. Screenshot:
<img width="444" alt="image" src="https://github.com/romis2012/pydantic-collections/assets/74110513/fd088507-ec41-49c1-9409-3ff69bef25f3">

Is this an issue with my static type checker or a limitation of the module?

**Comment by lbelangers** [comment]
To add to my last comment, ideally, my IDE would display `(variable) car: Car`

**Comment by romis2012** [comment]
I have provided the stub file int the latest version (0.5.4). It should fix the issue.

**Comment by lbelangers** [comment]
Amazing, it seems to have solved the issue. Can you close the issue when the new version is published to pypi?

**Comment by romis2012** [comment]
It's [published](https://pypi.org/project/pydantic-collections/0.5.4/)

**Comment by lbelangers** [comment]
Thank you!
